# Generated by Django 3.0.3 on 2020-02-09 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderAndTranslate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='originalbooks',
            name='unique_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
