# Generated by Django 3.0.3 on 2020-02-10 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderAndTranslate', '0002_originalbooks_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='originalbooks',
            name='book_url',
            field=models.URLField(default='', max_length=255, verbose_name='Books Url'),
        ),
        migrations.AddField(
            model_name='originalbookscontent',
            name='chapter_url',
            field=models.URLField(default='', max_length=255, verbose_name='Chapter Url'),
        ),
        migrations.AlterField(
            model_name='originalbookscontent',
            name='chapter_content',
            field=models.TextField(default='', verbose_name='Chapter Content'),
        ),
    ]
