# Generated by Django 3.0.3 on 2020-02-11 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spiderAndTranslate', '0003_auto_20200211_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='originalbooks',
            name='unique_id',
        ),
    ]
