# Generated by Django 3.0.3 on 2020-02-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderAndTranslate', '0004_remove_originalbooks_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='originalbooks',
            name='book_id',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='Book ID'),
        ),
    ]
