# Generated by Django 3.0.3 on 2020-02-11 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spiderAndTranslate', '0005_originalbooks_book_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='originalbooks',
            old_name='book_id',
            new_name='unique_id',
        ),
    ]
