# Generated by Django 3.0.3 on 2020-02-11 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderAndTranslate', '0007_auto_20200212_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanslationbookcontent',
            name='language_chapter',
            field=models.CharField(choices=[('EN', 'English'), ('VI', 'Vietnamese'), ('ES', 'Spanish'), ('FR', 'French'), ('ID', 'Indoesia'), ('MS', 'Malay')], max_length=2),
        ),
        migrations.AlterField(
            model_name='translationbooks',
            name='book_abstract',
            field=models.TextField(default='', verbose_name='Book Abstract'),
        ),
        migrations.AlterField(
            model_name='translationbooks',
            name='language_book',
            field=models.CharField(choices=[('EN', 'English'), ('VI', 'Vietnamese'), ('ES', 'Spanish'), ('FR', 'French'), ('ID', 'Indoesia'), ('MS', 'Malay')], max_length=2),
        ),
    ]
