# Generated by Django 3.0.3 on 2020-02-11 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderAndTranslate', '0008_auto_20200212_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originalbooks',
            name='book_abstract',
            field=models.TextField(default='', verbose_name='Book Abstract'),
        ),
        migrations.AlterField(
            model_name='originalbooks',
            name='book_category',
            field=models.CharField(default='', max_length=120, verbose_name='Book Category'),
        ),
    ]
