# Generated by Django 3.0.3 on 2020-02-21 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spiderAndTranslate', '0009_auto_20200212_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='TanslationBookContentEN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(default='', max_length=50, verbose_name='Chapter Name')),
                ('chapter_index', models.IntegerField(verbose_name='Chapter Index')),
                ('chapter_content', models.TextField(blank=True, verbose_name='Chapter Content')),
                ('words', models.IntegerField(verbose_name='Chapter words')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spiderAndTranslate.OriginalBooks', verbose_name='Book Information')),
            ],
            options={
                'verbose_name': 'Translation Book Content EN',
                'verbose_name_plural': 'Translation Book Content EN',
            },
        ),
        migrations.CreateModel(
            name='TanslationBookContentVI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(default='', max_length=50, verbose_name='Chapter Name')),
                ('chapter_index', models.IntegerField(verbose_name='Chapter Index')),
                ('chapter_content', models.TextField(blank=True, verbose_name='Chapter Content')),
                ('words', models.IntegerField(verbose_name='Chapter words')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spiderAndTranslate.OriginalBooks', verbose_name='Book Information')),
            ],
            options={
                'verbose_name': 'Translation Book Content',
                'verbose_name_plural': 'Translation Book Content',
            },
        ),
        migrations.CreateModel(
            name='TranslationBooksEN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(default='', max_length=120, verbose_name='Book Name')),
                ('book_author', models.CharField(default='', max_length=30, verbose_name='Book Author')),
                ('book_category', models.CharField(default='', max_length=120, verbose_name='Book Category')),
                ('book_tags', models.CharField(default='', max_length=120, verbose_name='Book Tags')),
                ('book_abstract', models.TextField(default='', verbose_name='Book Abstract')),
                ('total_words_tran', models.IntegerField(verbose_name='Book Total Words')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spiderAndTranslate.OriginalBooks', verbose_name='Book Information')),
            ],
            options={
                'verbose_name': 'Translation Books EN',
                'verbose_name_plural': 'Translation Books EN',
            },
        ),
        migrations.CreateModel(
            name='TranslationBooksVI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(default='', max_length=120, verbose_name='Book Name')),
                ('book_author', models.CharField(default='', max_length=30, verbose_name='Book Author')),
                ('book_category', models.CharField(default='', max_length=120, verbose_name='Book Category')),
                ('book_tags', models.CharField(default='', max_length=120, verbose_name='Book Tags')),
                ('book_abstract', models.TextField(default='', verbose_name='Book Abstract')),
                ('total_words_tran', models.IntegerField(verbose_name='Book Total Words')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spiderAndTranslate.OriginalBooks', verbose_name='Book Information')),
            ],
            options={
                'verbose_name': 'Translation Books VI',
                'verbose_name_plural': 'Translation Books VI',
            },
        ),
        migrations.RemoveField(
            model_name='translationbooks',
            name='book',
        ),
        migrations.DeleteModel(
            name='TanslationBookContent',
        ),
        migrations.DeleteModel(
            name='TranslationBooks',
        ),
    ]
