# Generated by Django 3.0.3 on 2020-02-22 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderAndTranslate', '0010_auto_20200222_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanslationbookcontenten',
            name='chapter_name',
            field=models.CharField(default='', max_length=150, verbose_name='Chapter Name'),
        ),
        migrations.AlterField(
            model_name='tanslationbookcontentvi',
            name='chapter_name',
            field=models.CharField(default='', max_length=150, verbose_name='Chapter Name'),
        ),
        migrations.AlterField(
            model_name='translationbooksen',
            name='book_author',
            field=models.CharField(default='', max_length=200, verbose_name='Book Author'),
        ),
        migrations.AlterField(
            model_name='translationbooksvi',
            name='book_author',
            field=models.CharField(default='', max_length=200, verbose_name='Book Author'),
        ),
    ]
