# Generated by Django 3.0.3 on 2020-02-22 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spiderAndTranslate', '0011_auto_20200223_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanslationbookcontenten',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spiderAndTranslate.TranslationBooksEN', verbose_name='Book Information'),
        ),
        migrations.AlterField(
            model_name='tanslationbookcontentvi',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spiderAndTranslate.TranslationBooksVI', verbose_name='Book Information'),
        ),
    ]
